import { createSlice } from '@reduxjs/toolkit';

// Define the initial state for the sound slice
const initialState = {
    soundsEnabled: true, // By default, sounds are enabled
};

// Create the sound slice using createSlice
const soundSlice = createSlice({
    name: 'sound', // A name for the slice, used in action types
    initialState,   // The initial state defined above
    reducers: {
        // Define a reducer function to toggle the soundsEnabled state
        toggleSounds: (state) => {
            state.soundsEnabled = !state.soundsEnabled; // Immer handles immutability
            // You might also want to save this to AsyncStorage here
            // For example: AsyncStorage.setItem('soundsEnabled', JSON.stringify(state.soundsEnabled));
        },
        // You could add other sound-related actions here, e.g., setVolume
        // setVolume: (state, action) => {
        //     state.volume = action.payload;
        // }
    },
});

// Export the action creator(s) generated by createSlice
export const { toggleSounds } = soundSlice.actions;

// Export the reducer function to be added to your Redux store
export default soundSlice.reducer;
